### ISSUE TITLE
Brightness control doesn't work with 2012 15" MacBook Pro

### ISSUE THREAD

**Issue by moosethegoose2213** [datcuandrei/i3wm-xfkeys#1]
By default it doesn't work with my 2012 15" MacBook Pro. Changing brightness.sh from saying "intel" to "gmux" seems to fix it though. Would changing it from `/sys/class/backlight/intel_backlight/brightness` to `/sys/class/backlight/*/brightness` be an alternative to fix this universally for MacBooks? You've done a really good job otherwise. Your Linux utilities work very well, thank you!

**Comment by datcuandrei** [comment]
Hi!Thank you for mentioning this issue and for using my software.

I'll fix and update this as soon as possible and I'll for sure take your suggestion in consideration.

**Comment by moosethegoose2213** [comment]
Also, if you have playerctl installed, I've also written a small shell script that adds support for multimedia buttons. That would mean that you either have to already have playerctl installed of have to install it before use though. Thanks for the consideration!

**Comment by datcuandrei** [comment]
Hi!Sorry for taking this long to reply.

The issue will be fixed this weekend,as I have no time to do much programming lately.Also,using `*` will not work,I'll make the script check if either `intel_backlight` or `gmux` exist,and if yes then continue running the script.

**Comment by datcuandrei** [comment]
The issue mentioned has been fixed with the release of i3wm-xfkeys v1.0
